name: Running
on:
  push:
    branches:
      - main
jobs:
  Alerts:
    runs-on: ubuntu-latest
    steps:
    - name: Downloading aws retriever
      run: |
        mkdir -p awsRetriever
        cd awsRetriever
        sudo apt-get install mono-complete -y
        wget https://github.com/dtylman/AWSRetriever/releases/download/rc3/AWSRetriever_0_1_0_14.zip
        unzip AWSRetriever_0_1_0_14.zip
        cd AWSRetriever_0_1_0_14
        ls
