name: Running
on:
  push:
    branches:
      - main
jobs:
  Alerts:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials for CLC Production
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-south-1"
    - name: Downloading aws retriever
      run: |
        mkdir -p awsRetriever
        cd awsRetriever
        sudo apt-get install mono-complete -y
        wget https://github.com/dtylman/AWSRetriever/releases/download/rc3/AWSRetriever_0_1_0_14.zip
        unzip AWSRetriever_0_1_0_14.zip
        cd AWSRetriever_0_1_0_14
        curl -O https://raw.githubusercontent.com/Adarshkumar14/aws-resource-alerts/main/ec2.profile.js
        mono AWSRetriever.exe -r -p default.profile.js -o objects.json
        cat objects.json
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.16.0
      with:
        payload: awsRetriever/AWSRetriever_0_1_0_14/objects.json # This data can be any valid JSON from a previous step in the GitHub Action
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
